export type DayStatistic = {
  startDay: string;
  endDay: string;
  totalHours: string;
  totalIsolatedPeriodHours: string;
  totalTimerHours: string;
  totalPomodoroHours: string;
  totalBreakHours: string;
  isolatedPeriodCount: number;
  totalTimeManual: string;
  timerCount: number;
  pomodoroCount: number;
  breakCount: number;
  sessionCount: number;
  timePeriodCount: number;
  timeMinuteCount: number;
  interruptionCount: number;
  manualCount: number;
  createdTimeRecordCount: number;
  updatedTimeRecordCount: number;
};
